export { default as TANGAN } from './cucitangan.svg'
export { default as JGNSENTUH } from './jgnsentuh.svg'
export { default as MASKER } from './masker.svg'
export { default as KESEHATAN } from './bantuan.svg'
export { default as NEWS } from './berita.svg'
export { default as SOCIAL_DISTANCING } from './pembatasan-sosial.svg'
export { default as BENDERA } from './indonesia.svg'
export { default as TIME } from './jam.svg'
export { default as INFO } from './info.svg'
export { default as VIRUS } from "./virus.svg"
export { default as BERSIN } from "./bersin.svg"
export { default as KUMPUL } from "./kumpul.svg" 
export { default as FB } from './fb.svg'
export { default as TW } from './tw.svg'
